<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb6364ff882a4e64e9014c110fb7c028f
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb6364ff882a4e64e9014c110fb7c028f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb6364ff882a4e64e9014c110fb7c028f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb6364ff882a4e64e9014c110fb7c028f::$classMap;

        }, null, ClassLoader::class);
    }
}
